version: '2'
services:
  nginx:
    image: wearelighthouse/nginx:wordpress
    ports:
     - 80:80
    volumes:
     - ../../../:/usr/share/nginx/html
    networks:
     - network
  fpm:
    image: wearelighthouse/php-fpm:latest
    volumes:
     - ../../../:/usr/share/nginx/html
    networks:
     - network
  db:
    image: mysql:5.7
    # Set max_allowed_packet to 256M (or any other value)
    command: --max_allowed_packet=64M
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
     - data:/var/lib/mysql
    networks:
     - network
networks:
  network:
    driver: bridge
volumes:
  data:
    driver: local
